install:
    before:
        - hisite

nginx:
    before:
        - hisite

hisite:
    path:   .
    web:
        assets:
            chmod: '0777'
        index.php:
            template: '@hidev/hisite/views/web/index.twig'
    runtime:
        chmod:  '0777'
    src:
        config:
            bootstrap.php:
                once:     true
                template: '@hidev/hisite/views/config/bootstrap.twig'
            hidev.php:
                once:     true
                template: '@hidev/hisite/views/config/hidev.twig'
            hisite.php:
                once:     true
                template: '@hidev/hisite/views/config/hisite.twig'
            params.php:
                class:    hisite-params
            web.php:
                once:     true
                template: '@hidev/hisite/views/config/web.twig'

