package:
    type:           yii2-extension
    name:           hidev-hisite
    title:          HiDev config for HiSite
    headline:       HiDev HiSite
    keywords:       hidev, hisite
    namespace:      hidev\hisite
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin provides HiDev configuration for [HiSite](https://github.com/hiqdev/hisite) web applications.

        Provides:

        - creating directories and files:
            - runtime/
            - web/assets/
            - web/index.php
            - src/_bootstrap.php
            - src/config/params.php  (if not exists)
            - src/config/common.php  (if not exists)
            - src/config/console.php (if not exists)
            - src/config/web.php     (if not exists)
        - setting permissions for directories and files
        - generation of nginx config

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
