package:
    type:           yii2-extension
    name:           hidev-hisite
    title:          HiDev config for HiSite
    headline:       HiDev HiSite
    keywords:       hidev, hisite
    namespace:      hidev\hisite
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin provides HiDev configuration for HiSite.

        [HiSite](https://github.com/hiqdev/hisite) is another way of building Yii2 based web applications.

        Provides:

        - creating directory structure and files:
            - `runtime/`
            - `web/assets/`
            - `web/index.php`
            - `src/config/bootstrap.php`
            - `src/config/defines.php`
            - `src/config/hidev.php`
            - `src/config/hisite.php`
            - `src/config/params.php`
            - `src/config/web.php`
        - setting permissions for directories and files
        - nginx config generation with help of `hidev-nginx` plugin

php-cs-fixer:
    finder:
        notPath:
            - tests/functional/minimal
            - src/views/hisite
