install:
    before:
        - yii2-web-app-dirs

yii2-web-app-dirs:
    path:   .
    class:  directory
    web:
        assets:
            chmod: '0777'
        index.php:
            template: '@hidev/yii2/webapp/views/web/index.twig'
    runtime:
        chmod:  '0777'
        nginx.conf:
            template: '@hidev/yii2/webapp/views/nginx.twig'
    src:
        _bootstrap.php:
            template: '@hidev/yii2/webapp/views/bootstrap.twig'
        config:
            params.php:
                once:     true
                template: '@hidev/yii2/webapp/views/config/params.twig'
            common.php:
                once:     true
                template: '@hidev/yii2/webapp/views/config/common.twig'
            console.php:
                once:     true
                template: '@hidev/yii2/webapp/views/config/console.twig'
            web.php:
                once:     true
                template: '@hidev/yii2/webapp/views/config/web.twig'

vcsignore:
    'runtime/*':    Yii2 web app directories
    'web/assets/*': Yii2 web app directories

