install:
    before:
        - hisite

hisite:
    path:   .
    web:
        assets:
            chmod: '0777'
        index.php:
            template: '@hidev/hisite/views/web/index.twig'
    runtime:
        chmod:  '0777'
        nginx.conf:
            template: '@hidev/hisite/views/nginx.twig'
    src:
        _bootstrap.php:
            once:     true
            template: '@hidev/hisite/views/bootstrap.twig'
        config:
            params.php:
                once:     true
                template: '@hidev/hisite/views/config/params.twig'
            common.php:
                once:     true
                template: '@hidev/hisite/views/config/common.twig'
            console.php:
                once:     true
                template: '@hidev/hisite/views/config/console.twig'
            web.php:
                once:     true
                template: '@hidev/hisite/views/config/web.twig'

vcsignore:
    'runtime/*':    HiSite directories
    'web/assets/*': HiSite directories

